### ISSUE TITLE
9.1.5 issue

### ISSUE THREAD

**Issue by hardvark** [solocommand/Socialite#31]
Hi Socialite not showing its frame today in 9.1.5.
Failing on GetBackdrop

Thanks :)

**Comment by VessoDaShaman** [comment]
Here is what I am seeing regarding that error as well if that helps anyone....

Socialite\tooltip.lua:208: attempt to call method 'GetBackdrop' (a nil value)
[string "@Socialite\tooltip.lua"]:208: in function `Clear'
[string "@Socialite\Socialite-9.1.0.lua"]:85: in function <Socialite\Socialite.lua:84>
[string "@Titan\LDBToTitan.lua"]:343: in function <Titan\LDBToTitan.lua:302>

**Comment by Tiiara** [comment]
1x Socialite\tooltip.lua:208: attempt to call method 'GetBackdrop' (a nil value)
[string "@Socialite\tooltip.lua"]:208: in function `Clear'
[string "@Socialite\Socialite-9.1.0.lua"]:85: in function <Socialite\Socialite.lua:84>
[string "@Titan\LDBToTitan.lua"]:343: in function <Titan\LDBToTitan.lua:302>

Locals:
self = <table> {
 Clear = <function> defined @Socialite\tooltip.lua:142
 AddHeader = <function> defined @Socialite\tooltip.lua:368
 SetLineScript = <function> defined @Socialite\tooltip.lua:537
 AddColspanHeader = <function> defined @Socialite\tooltip.lua:391
 AddColspanLine = <function> defined @Socialite\tooltip.lua:357
 AddLine = <function> defined @Socialite\tooltip.lua:332
 SmartAnchorTo = <function> defined @Socialite\tooltip.lua:633
 SetAutoHideDelay = <function> defined @Socialite\tooltip.lua:668
 Show = <function> defined @Socialite\tooltip.lua:716
 IsShown = <function> defined @Socialite\tooltip.lua:709
 IsVisible = <function> defined @Socialite\tooltip.lua:702
 Hide = <function> defined @Socialite\tooltip.lua:723
}
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 textLeft1Font = "GameTooltipHeaderText"
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 updateTooltipTimer = 0.060000
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 comparing = false
 SetSocketGem = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 SetInboxItem = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 waitingForData = false
 SetTrainerService = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 SetItemKey = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetWeeklyReward = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetExistingSocketGem = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 SetUnit = <function> defined =[C]:-1
 NineSlice = <unnamed> {
 }
 SetInventoryItem = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 layoutType = "TooltipDefaultLayout"
 CIMI_tooltipWritten = false
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetTradeTargetItem = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 textLeft2Font = "GameTooltipText"
 SetRecipeResultItem = <function> defined =[C]:-1
}
(*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"
tframe = <unnamed> {
 0 = <userdata>
 lines = <table> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:414
 scrollframe = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 columns = <table> {
 }
 height = 0
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 width = 12
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 scroller = <unnamed> {
 }
 SetupPieceVisuals = <function> def

**Comment by solocommand** [comment]
Thanks all, I haven't had a chance to boot up the game yet. Will take a look tonight.

**Comment by solocommand** [comment]
This is now resolved with the latest release, please update and let me know if you see any further issues!
