### ISSUE TITLE
Socialite Replaced by Scoreboard

### ISSUE THREAD

**Issue by kstange** [solocommand/Socialite#34]
Hi,

It looks like the releases for scoreboard and socialite got mixed together in Curse and the app automatically updated Socialite to Scoreboard 10.0.0.  I had to manually roll it back.

**Comment by solocommand** [comment]
Thanks for the report. This should be resolved with the latest Socialite alpha, which should be available in the Curse client now. Can you try updating to the alpha and let me know if the correct addon is installed now?

Thanks!

**Comment by kstange** [comment]
That didn't seem to help. I think the problem is that the Socialite-10.0.0.zip file is uploaded to both the Socialite and Scoreboard releases on CurseForge, while Scoreboard still has its own releases as well.  After updating to Socialite-10.0.0.zip, CurseForge gets confused and thinks I'm on a Scoreboard release file, and then sees the Scoreboard-10.0.0.zip version as an update and installs that.  I guess the fix would be to delete the duplicates from the Scoreboard curseforge project if that's possible and then hopefully CurseForge will just automatically see the file as part of Socialite again.  If not, maybe you'd need to re-release Socialite with version 10.0.1 and people will have to manually reinstall and then it will stick.

**Comment by solocommand** [comment]
Ah yeah, that might do it. Socialite's been re-released, and that copy of socialite has been removed from the scoreboard files on curseforge

**Comment by kstange** [comment]
It looks like everything is behaving now.  Thanks!
