### ISSUE TITLE
LUA error with TWW Pre-Patch

### ISSUE THREAD

**Issue by Poisonenvy2** [solocommand/Socialite#43]
1x Socialite/config.lua:256: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@Socialite/config.lua"]:256: in main chunk

Locals:
addonName = "Socialite"
addon = <table> {
 tooltip = <table> {
 }
 dataobj = <table> {
 }
 frame = Frame {
 }
 L = <table> {
 }
}
L = <table> {
 MENU_INTERACTION_NEVER_DESCRIPTION = "MENU_INTERACTION_NEVER_DESCRIPTION"
 MENU_GUILD_SORT_NAME_DESCRIPTION = "Sort by guild member name"
 MENU_GUILD_SORT = "Sort by"
 Guild Members = "Guild Members"
 Character Friends = "Character Friends"
 MENU_STATUS_ICON_DESCRIPTION = "When selected, the friend's status will be displayed by an icon, such as |TInterface\FriendsFrame\StatusIcon-DnD:0|t"
 MENU_STATUS_NONE_DESCRIPTION = "When selected, the friend's status will not be displayed."
 MENU_STATUS_NONE = "None"
 ShowRealIDNotesDescription = "Show your friends' note"
 ShowRealIDBroadcasts = "Show broadcasts/toasts"
 TOOLTIP_REMOTE_CHAT = "Remote Chat"
 ShowRealIDAppDescription = "If enabled, show all Battle.net friends, regardless of in-game status."
 ShowGuildLabel = "Show guild label"
 MENU_STATUS = "Show status as"
 ShowRealIDDescription = "Show friends in the data text and tooltip."
 ShowFriendsNote = "Show friend note"
 DisableUsageText = "Disable usage text"
 MENU_GUILD_SORT_LEVEL = "Level"
 TOOLTIP_FRIENDS = "Friends Online"
 ShowRealIDFactionsDescription = "Show the faction of your Battle.net friends"
 Show minimap button = "Show minimap button"
 TOOLTIP = "Social"
 ShowGuildLabelDescription = "If enabled, the data text will be prefixed with the guild name."
 Battle.net Friends = "Battle.net Friends"
 ShowRealIDBroadcastsDescription = "Show Battle.net friend broadcasts in the tooltip."
 MENU_STATUS_ICON = "Icon"
 MENU_GUILD_SORT_NOTE_DESCRIPTION = "Sort by guild member note"
 GuildSort = "Custom Sort"
 ShowGuildONote = "Show officer note"
 DisableUsageTextDescription = "If checked, the usage instructions will not be shown on the tooltip."
 ShowStatus = "ShowStatus"
 Socialite = "Socialite"
 MENU_STATUS_TEXT_DESCRIPTION = "When selected, the friend's status will be indicated by a text string, such as <Away>"
 ShowSplitRemoteChatDescription = "If enabled, guild members utilizing the remote chat feature will be displayed separately within the data text and tooltip."
 GuildSortAscendingDescription = "Sort in ascending (1..9 or A...Z) order"
 MENU_INTERACTION_OOC = "Out Of Combat"
 TOOLTIP_GUILD = "Guild Members Online"
 GuildSortKey = "GuildSortKey"
 MENU_INTERACTION = "Tooltip interaction"
 GuildSortAscending = "Ascending"
 ShowLabelDescription = "If enabled, the addon label (or guild name, if enabled) will be shown in the data text."
 TOOLTIP_REALID_APP = "Battle.net Friends in App"
 ShowLabel = "Show label"
 TOOLTIP_REALID = "Battle.net Friends Online"
 MENU_GUILD_SORT_RANK = "Rank"
 ShowGroupMembers = "Show Group Members"
 ShowFriends = "Show friends"
 MENU_INTERACTION_ALWAYS = "Always"
 usageDescription = "Left-click to view social panes. Alt+Click to invite. Right-click to configure."
 MENU_INTERACTION_DESCRIPTION = "When should the tooltip be interactable?"
 ShowGuildDescription = "If enabled, display guild members on the tooltip."
 ShowGuild = "Show guild members"
 ShowRealID = "Show friends"
 Display Settings = "Display Settings"
 MENU_GUILD_SORT_ZONE_DESCRIPTION = "Sort by guild member zone/login date"
 MENU_GUILD_SORT_NAME = "Name"
 Guild Sorting = "Guild Sorting"
 ShowFriendsDescription = "Include character friends in the tooltip"
 MENU_GUILD_SORT_NOTE = "Note"
 TooltipInteraction = "TooltipInteraction"
 ShowRealIDApp = "Show non-playing friends"
 MENU_GUILD_SORT_CLASS = "Class"
 ShowGuildNoteDescription = "If enabled, the guild member's public note will be displayed in the tooltip."
 MENU_STATUS_DESCRIPTION = "Show friend's online presence as..."
 MENU_GUILD_SORT_RANK_DESCRIPTION = "Sort by guild member rank"
 ShowGroupMembersDescription = "Show an indicator icon next to a friend when in the same group"
 MENU_GUILD_SORT_ZONE = "Zone"
 ShowRealIDFactions = "Show friends faction"
 ShowFriendsNoteDescription = "Show your character friends' note"
 MENU_INTERACTION_OOC_DESCRIPTION = "MENU_INTERACTION_OOC_DESCRIPTION"
 MENU_GUILD_SORT_CLASS_DESCRIPTION = "Sort by guild memb

**Comment by solocommand** [comment]
Hi there,

Thanks for the report! This has been resolved in the latest release. You can download it from the [releases](https://github.com/solocommand/Socialite/releases) page, or with your addon manager of choice.
