### ISSUE TITLE
Error: Couldn't open Socialite/vendor/AceConsole-3.0-7/AceConsole-3.0.xml

### ISSUE THREAD

**Issue by CherylAoife** [solocommand/Socialite#44]
2x Socialite/embeds.xml:8 Couldn't open Socialite/vendor/AceConsole-3.0-7/AceConsole-3.0.xml

**Comment by solocommand** [comment]
Hi there,

Thanks for the report! This has been resolved in the latest release. You can download it from the [releases](https://github.com/solocommand/Socialite/releases) page, or with your addon manager of choice.
