### ISSUE TITLE
Stop work in 11.0.5

### ISSUE THREAD

**Issue by kaiseryoda** [solocommand/Socialite#48]
Erros from bug graber

 

27x Socialite/Socialite.lua:159: attempt to concatenate local 'online' (a nil value)
[string "@Socialite/Socialite.lua"]:159: in function <Socialite/Socialite.lua:118>

Locals:
text = "|cffffd200Proud: |r"
comps = <table> {
1 = "|cff00A2E843|r"
2 = "|cffFFFFFF0|r"
}
showRealID = true
showRealIDApp = false
online = 17
remote = nil
_ = 477
online = nil
remote = nil
(*temporary) = <table> {
1 = "|cff00A2E843|r"
2 = "|cffFFFFFF0|r"
}
(*temporary) = "|cff00FF00"
(*temporary) = nil
(*temporary) = "|r"
(*temporary) = "attempt to concatenate local 'online' (a nil value)"
addon = <table> {
tooltip = <table> {
}
optionsFrame = Frame {
}
dataobj = <table> {
}
frame = Frame {
}
db = <table> {
}
L = <table> {
}
}
L = <table> {
MENU_INTERACTION_NEVER_DESCRIPTION = "MENU_INTERACTION_NEVER_DESCRIPTION"
MENU_GUILD_SORT_NAME_DESCRIPTION = "Sort by guild member name"
MENU_GUILD_SORT = "Sort by"
Guild Members = "Guild Members"
Character Friends = "Character Friends"
MENU_STATUS_ICON_DESCRIPTION = "When selected, the friend's status will be displayed by an icon, such as |TInterface\FriendsFrame\StatusIcon-DnD:0|t"
MENU_STATUS_NONE_DESCRIPTION = "When selected, the friend's status will not be displayed."
MENU_STATUS_NONE = "None"
ShowRealIDNotesDescription = "Show your friends' note"
ShowRealIDBroadcasts = "Show broadcasts/toasts"
TOOLTIP_REMOTE_CHAT = "Remote Chat"
ShowRealIDAppDescription = "If enabled, show all Battle.net friends, regardless of in-game status."
ShowGuildLabel = "Show guild label"
MENU_STATUS = "Show status as"
ShowRealIDDescription = "Show friends in the data text and tooltip."
ShowFriendsNote = "Show friend note"
DisableUsageText = "Disable usage text"
MENU_GUILD_SORT_LEVEL = "Level"
TOOLTIP_FRIENDS = "Friends Online"
ShowRealIDFactionsDescription = "Show the faction of your Battle.net friends"
Show minimap button = "Show minimap button"
TOOLTIP = "Social"
ShowGuildLabelDescription = "If enabled, the data text will be prefixed with the guild name."
Battle.net Friends = "Battle.net Friends"
ShowRealIDBroadcastsDescription = "Show Battle.net friend broadcasts in the tooltip."
MENU_STATUS_ICON = "Icon"
MENU_GUILD_SORT_NOTE_DESCRIPTION = "Sort by guild member note"
GuildSort = "Custom Sort"
ShowLabelDescription = "If enabled, the addon label (or guild name, if enabled) will be shown in the data text."
ShowGuildONote = "Show officer note"
DisableUsageTextDescription = "If checked, the usage instructions will not be shown on the tooltip."
ShowStatus = "ShowStatus"
Socialite = "Socialite"
MENU_STATUS_TEXT_DESCRIPTION = "When selected, the friend's status will be indicated by a text string, such as <Away>"
ShowLabel = "Show label"
ShowSplitRemoteChatDescription = "If enabled, guild members utilizing the remote chat feature will be displayed separately within the data text and tooltip."
GuildSortAscendingDescription = "Sort in ascending (1..9 or A...Z) order"
ShowRealID = "Show friends"
MENU_INTERACTION_ALWAYS_DESCRIPTION = "MENU_INTERACTION_ALWAYS_DESCRIPTION"
ShowGroupMembers = "Show Group Members"
TOOLTIP_GUILD = "Guild Members Online"
GuildSortKey = "GuildSortKey"
ShowSplitRemoteChat = "Separate remote chat"
GuildSortAscending = "Ascending"
usageDescription = "Left-click to view social panes. Alt+Click to invite. Right-click to configure."
TOOLTIP_REALID_APP = "Battle.net Friends in App"
MENU_INTERACTION = "Tooltip interaction"
TOOLTIP_REALID = "Battle.net Friends Online"
Display Settings = "Display Settings"
MENU_GUILD_SORT_ZONE_DESCRIPTION = "Sort by guild member zone/login date"
ShowFriends = "Show friends"
MENU_INTERACTION_ALWAYS = "Always"
MENU_STATUS_TEXT = "Text"
MENU_INTERACTION_DESCRIPTION = "When should the tooltip be interactable?"
ShowGuildDescription = "If enabled, display guild members on the tooltip."
ShowGuild = "Show guild members"
Guild Sorting = "Guild Sorting"
showInAddonCompartmentDescription = "Toggles the display of Socialite within the addon compartment."
MENU_GUILD_SORT_NOTE = "Note"
ShowRealIDApp = "Show non-playing friends"
MENU_GUILD_SORT_CLASS = "Class"
Data text = "Data text"
MENU_GUILD_SORT_RANK_DESCRIPTION = "Sort by guild member rank"
TooltipInteraction = "TooltipInteraction"
MENU_GUILD_

 

 

1x Socialite/functions.lua:700: 'for' limit must be a number
[string "=[C]"]: in function `error'
[string "@Socialite/Socialite.lua"]:193: in function `updateTooltip'
[string "@Socialite/Socialite.lua"]:96: in function `OnEnter'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:228: in function `func'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:102: in function <...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:92>

Locals:

**Comment by solocommand** [comment]
Hello,

This is resolved in the latest version. Thanks for the report!
